# Generated by Django 5.2.8 on 2026-02-21 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=255)),
                ('current_load', models.IntegerField(default=0)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing.businessunit')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('segment', models.CharField(max_length=50)),
                ('address_text', models.TextField()),
                ('ai_type', models.CharField(max_length=100, null=True)),
                ('ai_sentiment', models.CharField(max_length=50, null=True)),
                ('ai_priority', models.IntegerField(null=True)),
                ('ai_language', models.CharField(default='RU', max_length=10)),
                ('ai_summary', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='routing.manager')),
            ],
        ),
    ]
