# Generated by Django 5.2.8 on 2026-02-21 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessunit',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='businessunit',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ai_language',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ai_priority',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ai_sentiment',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ai_summary',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ai_type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_manager',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='manager',
            name='position',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='manager',
            name='skills',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='guid',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='segment',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='RoutingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_type', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_sentiment', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_language', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_priority', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routing.manager')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_result', to='routing.ticket')),
            ],
        ),
    ]
