# Generated by Django 5.2.8 on 2026-02-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_remove_businessunit_lat_remove_businessunit_lon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='address_text',
        ),
        migrations.AddField(
            model_name='ticket',
            name='attachments',
            field=models.TextField(blank=True, null=True, verbose_name='Вложения'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='birth_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Населённый пункт'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Пол клиента'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='house',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='guid',
            field=models.CharField(max_length=255, unique=True, verbose_name='GUID клиента'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='segment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Сегмент клиента'),
        ),
    ]
