# Generated by Django 5.2.8 on 2026-02-21 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0003_remove_ticket_address_text_ticket_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routingresult',
            name='ai_assigned_office',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Офис Назначения'),
        ),
        migrations.AddField(
            model_name='routingresult',
            name='ai_segment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Сегмент (ИИ)'),
        ),
        migrations.AddField(
            model_name='routingresult',
            name='manager_recommendations',
            field=models.TextField(blank=True, null=True, verbose_name='Рекомендации менеджеру'),
        ),
        migrations.AlterField(
            model_name='routingresult',
            name='ai_language',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='routingresult',
            name='ai_priority',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='routingresult',
            name='ai_sentiment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тональность'),
        ),
        migrations.AlterField(
            model_name='routingresult',
            name='ai_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='routingresult',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routing.manager', verbose_name='Назначенный Менеджер'),
        ),
        migrations.AlterField(
            model_name='routingresult',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_result', to='routing.ticket', verbose_name='Тикет'),
        ),
    ]
