# Generated by Django 5.2.8 on 2026-02-22 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0005_routingresult_new_csv_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingresult',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routing.manager', verbose_name='FK Менеджер'),
        ),
    ]
